### ISSUE TITLE
Usage 

### ISSUE THREAD

**Issue by mistaox** [stevemuller04/evrecovery#1]
I have a set of files on an external HDD  that look  like this:

D1402D4413941D3A197D3D7D2336F061.DVS
D1402D4413941D3A197D3D7D2336F061~C5~F1034F2B~00~1.DVSCC
D1402D4413941D3A197D3D7D2336F061~C5~F1034F2B~00~1.DVSSP

When I try to use dvsrestore, I get  mostly 0 kb files for attachments and no message bodies.
Any help would be greatly appreciated.

Thanks

**Comment by stevemuller04** [comment]
I can't tell for sure since there seem to be major changes in the file format for different Enterprise Vault versions.
The dvsrestore utility is very specific to a particular CFBF file structure, so it may not find the payload where it expects it to be.
Have you tried analysing the file in question with `cfbfdump list --input $CFBFFILE`? It may give hints on the file structure in your case.

**Comment by mistaox** [comment]
First of all, thank you for responding!

I was told these files are from EV 11.
When I try cfbfdump.exe list --input , I get the following error:
**"I/O ERROR: failed to fill whole buffer"**

I've attached a sample if you would like to take a look.
[DVSTest.zip](https://github.com/stevemuller04/evrecovery/files/4968442/DVSTest.zip)

**Comment by stevemuller04** [comment]
Thanks. I will have a look on the weekend.

**Comment by stevemuller04** [comment]
It looks like your DVS files contain an (empty) `FileContentStream` section, even though the content has been out-sourced! Moreover, the out-sourced file has a different file extension (`dvssp`) than in my case (`dvf`).
I made two changes to the tool (v1.1.0):
- change the order in which the content is searched for (first out-sourced, then embedded)
- add possibility to specify file extension of out-sourced file with the `--ext` flag

Please let me know if it worked out for you.

**Comment by mistaox** [comment]
That seems to have done the trick.
I'll keep testing.

Any chance of a C# version? Im new to RUST. Perhaps I can convert it to a .net  library.
Thanks!

**Comment by stevemuller04** [comment]
Unfortunately I do not have the time to do this right now. But feel free to provide an implementation on your own. You can read the [Journey](https://github.com/stevemuller04/evrecovery/blob/master/Journey.md) to get an insight on the DVS file format (it's basically a wrapper for a zipped [CFBF](https://en.wikipedia.org/wiki/Compound_File_Binary_Format) file). There are C# implementations for both ZLIB and for CFBF/CDF files (for the latter, I've found e.g. https://sourceforge.net/projects/openmcdf/, but I haven't tested it).

**Comment by mistaox** [comment]
5 years later. Did you look further into the objects stored in the "ExchVStore"?
